name: Docker Image CI

on:
  push:
#    tags:
#    - 'v[0-9]+.[0-9]+.[0-9]+'
    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Get package version
      id: package-version
      uses: koj-co/package-version-action@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Appliaction version condition
      run: |
        if [ "${{github.ref}}" != "${{ steps.package-version.outputs.package-version }}" ]; then
          echo "Wrong versions ${{github.ref}} ${{ steps.package-version.outputs.package-version }}"
          exit 1
        fi
   
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/temp-test:latest, ${{ secrets.DOCKERHUB_USERNAME }}/temp-test:${{ steps.package-version.outputs.package-version }}

#    - name: Build the Docker image
#      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
